-- Migration: 조류 종 시드 데이터 Batch 5 (65종) — 참새목 소형조류
-- Date: 2026-04-04
-- Description: 희귀종 4종 + 나그네새 28종 + 텃새 33종
-- Source: IOC World Bird List v14.x, NIBR 한국 조류 체크리스트
-- Depends: 20260404_000001_create_species_table.sql

-- UP
BEGIN;

-- ============================================================
-- SECTION 1: 희귀종 (Rare) — points=10, is_locked_free=TRUE
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-286', 'ioc14-emb-aur', '검은머리쑥새', 'Emberiza aureola', 'Yellow-breasted Bunting',
  '참새목', '멧새과', 'rare', 2, 10,
  3, TRUE, NULL, 'CR',
  15,
  '농경지와 갈대밭을 이동 시 경유하는 나그네새로 과거 한국에서 흔했으나 현재 CR 등급',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '검은머리쑥새는 포획·밀렵으로 30년 만에 전 세계 개체 수가 90% 감소한 비극적인 CR 등급 철새입니다'),

('KR-287', 'ioc14-loc-ple', '섬개개비', 'Locustella pleskei', 'Styan''s Grasshopper Warbler',
  '참새목', '개개비사촌과', 'rare', 2, 10,
  4, TRUE, NULL, 'VU',
  14,
  '제주도와 서해 도서 풀밭에서 번식하는 VU급 한국 준고유종',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '섬개개비는 제주도와 서해 무인도에서만 번식하는 한국 거의 유일한 서식지를 가진 귀한 새입니다'),

('KR-288', 'ioc14-fal-amo', '쇠황조롱이', 'Falco columbarius', 'Merlin',
  '매목', '매과', 'rare', 3, 10,
  3, TRUE, NULL, 'LC',
  30,
  '개활지와 해안 초지에서 드물게 월동하며 소형 조류를 추격해 잡는 소형 맹금류',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '쇠황조롱이는 황조롱이와 달리 호버링 없이 스피드로 먹이를 쫓아 잡는 전력 질주형 맹금류입니다'),

('KR-289', 'ioc14-bom-jap', '홍여새', 'Bombycilla japonica', 'Japanese Waxwing',
  '참새목', '여새과', 'rare', 3, 10,
  2, TRUE, NULL, 'NT',
  18,
  '오렌지빛 꼬리 끝과 붉은 날개 반점이 특징인 불규칙 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '홍여새는 매년 겨울 한국을 찾는 수가 크게 달라 "풍년새"로 불리며 많이 오는 해는 길조로 여깁니다');

-- ============================================================
-- SECTION 2: 나그네새 (Migrant) — sensitivity_tier=3, points=3
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-290', 'ioc14-zoo-aur', '호랑지빠귀사촌', 'Zoothera sibirica', 'Siberian Thrush',
  '참새목', '지빠귀과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  23,
  '산림을 이동 시 경유하는 나그네새로 수컷의 청회색 체색이 인상적이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '시베리아지빠귀 수컷은 어두운 청회색이지만 암컷은 갈색으로 같은 종의 암수가 전혀 달라 보입니다'),

('KR-291', 'ioc14-phy-cor', '산솔새', 'Phylloscopus coronatus', 'Eastern Crowned Warbler',
  '참새목', '솔새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  12,
  '산지 낙엽수림에서 번식하며 "삐리리삐리리" 명랑한 소리로 우는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '산솔새의 머리 정중선 흰 줄은 솔새류 동정의 핵심 포인트로 이 줄 하나에 탐조인들의 눈이 집중됩니다'),

('KR-292', 'ioc14-phy-bor', '되솔새', 'Phylloscopus borealis', 'Arctic Warbler',
  '참새목', '솔새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  12,
  '산림과 공원을 이동 시 통과하며 활발하게 나뭇잎을 뒤지는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '되솔새는 북극권에서 번식해 동남아까지 이동하는 장거리 철새로, 한국을 봄가을 정기 경유지로 씁니다'),

('KR-293', 'ioc14-phy-ten', '두견솔새', 'Phylloscopus tenellipes', 'Pale-legged Leaf Warbler',
  '참새목', '솔새과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  12,
  '산림 하층 습한 곳을 이동 시 경유하는 나그네새로 흰다리가 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '두견솔새는 비슷한 솔새류 중 창백한 다리색으로 구별되며 소리는 "두견이" 울음을 흉내낸다는 설이 있습니다'),

('KR-294', 'ioc14-hor-dio', '휘파람새', 'Horornis diphone', 'Japanese Bush Warbler',
  '참새목', '휘파람새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  16,
  '산림 덤불과 공원에서 번식하며 "호-호케쿄" 청아한 소리로 우는 여름철새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '휘파람새 수컷의 복잡한 노래는 겨울 내내 혼자 연습해 봄에 완성시키는 1인 리사이틀입니다'),

('KR-295', 'ioc14-acr-ori', '개개비', 'Acrocephalus orientalis', 'Oriental Reed Warbler',
  '참새목', '갈대개개비과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  19,
  '갈대밭과 수초 습지에서 번식하며 "갸갸갸갸" 요란한 소리로 우는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '개개비는 갈대 줄기 사이에서 포식자를 두려워 않고 맞서 울며 영역을 지키는 담대한 새입니다'),

('KR-296', 'ioc14-acr-bis', '쇠개개비', 'Acrocephalus bistrigiceps', 'Black-browed Reed Warbler',
  '참새목', '갈대개개비과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  13,
  '갈대밭과 논 경계 수초에서 번식하는 소형 개개비',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠개개비는 눈 위 검은 줄이 선명해 "검은눈썹개개비"로도 불리며 갈대숲 속에서 살살 움직입니다'),

('KR-297', 'ioc14-acr-aru', '큰개개비', 'Acrocephalus arundinaceus', 'Great Reed Warbler',
  '참새목', '갈대개개비과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  20,
  '넓은 갈대밭에서 번식하며 갈대 꼭대기에서 음량 가득 노래하는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '큰개개비는 갈대밭의 "록스타"로, 텃새 대비 몸의 2배 크기의 폐로 귀청이 떨어질 듯 노래합니다'),

('KR-298', 'ioc14-emb-ele', '노랑턱멧새', 'Emberiza elegans', 'Yellow-throated Bunting',
  '참새목', '멧새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  16,
  '산림과 덤불에서 번식하며 노란 목이 선명한 여름철새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '노랑턱멧새의 노란 목 반점은 번식기 수컷에서 가장 선명하며, 덤불 위에서 청아한 노래를 반복합니다'),

('KR-299', 'ioc14-emb-spo', '촉새', 'Emberiza spodocephala', 'Masked Bunting',
  '참새목', '멧새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  16,
  '산림 하층과 덤불에서 겨울을 나는 멧새로 수컷의 회색 얼굴 가면이 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '촉새는 한겨울 덤불 속에서 조용히 지내다 봄이 되면 드디어 노래하기 시작하는 수줍은 겨울새입니다'),

('KR-300', 'ioc14-emb-rus', '쑥새', 'Emberiza rustica', 'Rustic Bunting',
  '참새목', '멧새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'VU',
  15,
  '농경지와 덤불에서 겨울을 나는 멧새로 수컷의 검은 머리와 흰 눈썹이 선명하다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '쑥새는 VU 등급으로 분류될 만큼 빠르게 감소하고 있으며, 이름처럼 쑥밭에서 즐겨 먹이를 찾습니다'),

('KR-301', 'ioc14-emb-pal', '흰배멧새', 'Emberiza pallasi', 'Pallas''s Reed Bunting',
  '참새목', '멧새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  14,
  '갈대밭과 농경지에서 드물게 월동하는 소형 멧새로 작은 몸집이 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '흰배멧새는 극동지방과 시베리아에서 번식해 한국 남부까지 내려오는 작고 귀여운 겨울 멧새입니다'),

('KR-302', 'ioc14-mot-yar', '알락할미새', 'Motacilla yarrellii', 'Pied Wagtail',
  '참새목', '할미새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  18,
  '강가와 해안을 이동 시 드물게 경유하는 흑백 할미새로 흰할미새와 유사하다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '알락할미새는 흰할미새의 유럽 아종이 독립종으로 분리된 경우로, 한국 기록이 소수에 불과합니다'),

('KR-303', 'ioc14-mot-lug', '검은등할미새', 'Motacilla lugens', 'White Wagtail (lugens)',
  '참새목', '할미새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  19,
  '해안과 강가에서 흰할미새와 함께 겨울을 나며 등 전체가 검은 것이 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '검은등할미새는 등이 검어 흰할미새와 구별되며, 꼬리를 항상 위아래로 흔들며 걷는 할미새 특유의 행동을 합니다'),

('KR-304', 'ioc14-ant-ric', '긴발톱할미새', 'Anthus richardi', 'Richard''s Pipit',
  '참새목', '할미새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  18,
  '농경지와 개활지를 이동 시 통과하는 대형 밭종다리로 긴 뒷발톱이 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '긴발톱할미새의 뒷발톱은 몸길이의 절반에 달해 풀밭 위에서 안정적으로 서 있을 수 있게 합니다'),

('KR-305', 'ioc14-ant-god', '밭종다리', 'Anthus godlewskii', 'Blyth''s Pipit',
  '참새목', '할미새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  17,
  '건조한 농경지와 풀밭에서 드물게 월동하는 밭종다리류',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '밭종다리는 긴발톱할미새와 매우 유사해 두 종의 야외 구별은 조류 관찰의 난이도 최상급 과제입니다'),

('KR-306', 'ioc14-ant-spi', '논종다리', 'Anthus spinoletta', 'Water Pipit',
  '참새목', '할미새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  17,
  '논, 습지, 하천변에서 겨울을 나는 논종다리로 물가를 선호한다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '논종다리는 물 위를 걸을 것처럼 습지 가장자리를 섬세한 발걸음으로 걷는 모습이 인상적입니다'),

('KR-307', 'ioc14-bom-gar', '황여새', 'Bombycilla garrulus', 'Bohemian Waxwing',
  '참새목', '여새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  19,
  '불규칙적으로 한국에 무리지어 내려오며 과실을 탐식하는 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '황여새는 북방 침엽수림의 열매 결실에 따라 남하 여부가 달라지는 "어간 철새"로 많이 오면 화제가 됩니다'),

('KR-308', 'ioc14-coc-coc', '콩새', 'Coccothraustes coccothraustes', 'Hawfinch',
  '참새목', '되새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  18,
  '활엽수림과 과수원에서 겨울을 나며 씨앗을 굵은 부리로 깨 먹는 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '콩새의 부리 근육은 체중의 1/3에 달해 70kg 무게를 버티는 힘으로 버찌 씨앗을 깨뜨립니다'),

('KR-309', 'ioc14-pyr-pyr', '멋쟁이새', 'Pyrrhula pyrrhula', 'Eurasian Bullfinch',
  '참새목', '되새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  17,
  '침엽수림과 혼효림에서 겨울을 나며 수컷의 붉은 가슴이 아름다운 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '멧쟁이새는 과거 유럽에서 노래 잘하는 새를 선발해 피리로 가르치는 훈련에 쓰인 영리한 새입니다'),

('KR-310', 'ioc14-car-ros', '양진이', 'Carpodacus roseus', 'Pallas''s Rosefinch',
  '참새목', '되새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  16,
  '산림과 덤불에서 드물게 월동하며 수컷의 분홍빛이 아름다운 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '양진이 수컷의 분홍 체색은 먹는 색소 성분에 따라 달라지며, 먹이가 풍부할수록 더 진한 분홍빛을 냅니다'),

('KR-311', 'ioc14-lox-cur', '솔잣새', 'Loxia curvirostra', 'Red Crossbill',
  '참새목', '되새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  16,
  '침엽수림에서 솔방울 씨앗을 먹으며 불규칙 겨울철새로 나타나는 교차 부리의 새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '솔잣새의 X자로 교차한 부리는 솔방울 비늘을 비틀어 씨앗을 꺼내는 특수 도구로 진화한 자연의 걸작입니다'),

('KR-312', 'ioc14-fri-coe', '되새', 'Fringilla coelebs', 'Common Chaffinch',
  '참새목', '되새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  15,
  '산림과 공원에서 드물게 월동하는 서방 되새로 한국에서는 희귀한 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '흔히 알려진 되새(Brambling)와 이름이 혼동되지만 Common Chaffinch는 별개종으로 한국에서 드물게 기록됩니다'),

('KR-313', 'ioc14-ura-squ', '숲새', 'Urosphena squameiceps', 'Asian Stubtail',
  '참새목', '휘파람새과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  10,
  '낙엽수림 바닥층을 이동 시 경유하며 꼬리가 매우 짧은 소형 휘파람새류',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '숲새는 꼬리가 거의 없어 쥐처럼 바닥을 달리는 모습으로 솔새류 중 가장 기이한 외모를 가집니다'),

('KR-314', 'ioc14-cal-bra', '쇠종다리', 'Calandrella brachydactyla', 'Greater Short-toed Lark',
  '참새목', '종다리과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  14,
  '농경지와 건조한 초지를 드물게 이동 시 통과하는 희귀 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠종다리는 짧은 부리와 납작한 체형이 특징으로, 한국에 오면 즉시 희귀 기록으로 보고됩니다'),

('KR-315', 'ioc14-phy-hum', '흰눈썹솔새', 'Phylloscopus humei', 'Hume''s Leaf Warbler',
  '참새목', '솔새과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  10,
  '산림과 덤불을 드물게 이동 시 통과하는 나그네새로 쇠솔새와 유사하다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '흰눈썹솔새는 고분자 DNA 분석으로 쇠솔새에서 분리된 종으로, 야외에서 구별하기 가장 어려운 솔새입니다'),

('KR-316', 'ioc14-agr-phi', '쇠찌르레기', 'Agropsar philippensis', 'Chestnut-cheeked Starling',
  '참새목', '찌르레기과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  19,
  '과수원과 산림 가장자리를 이동 시 통과하는 나그네새로 밤색 뺨이 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠찌르레기는 찌르레기 무리에 섞여 이동하다 꼼꼼한 관찰자에 의해 발견되는 숨은 보석 나그네새입니다');

-- ============================================================
-- SECTION 3: 텃새/흔한 참새목 (Common) — sensitivity_tier=3, points=1
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-317', 'ioc14-ala-arv', '종다리', 'Alauda arvensis', 'Eurasian Skylark',
  '참새목', '종다리과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  19,
  '농경지와 초지에서 번식하며 하늘 높이 올라 노래하는 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '종다리는 수직으로 100m 이상 상승하며 1시간 넘게 연속 노래하는 비행 음악가입니다'),

('KR-318', 'ioc14-mot-cit', '시베리아할미새', 'Motacilla citreola', 'Citrine Wagtail',
  '참새목', '할미새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  19,
  '논, 습지, 강가를 이동 시 통과하는 노란 할미새로 머리가 밝은 노랑이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '시베리아할미새의 선명한 레몬 노랑 머리는 봄 이동 시 논에서 가장 눈에 띄는 할미새입니다'),

('KR-319', 'ioc14-mot-flu', '노랑발노랑할미새', 'Motacilla flava', 'Western Yellow Wagtail',
  '참새목', '할미새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  17,
  '논과 습지를 이동 시 통과하며 발이 노란 것이 특징인 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '노랑발노랑할미새는 수십 개의 아종이 있으며 머리색이 다양해 필드에서 동정이 까다로운 할미새입니다'),

('KR-320', 'ioc14-car-spi', '방울새사촌', 'Carduelis spinus', 'Eurasian Siskin',
  '참새목', '되새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  12,
  '침엽수림과 공원에서 겨울을 나며 솔방울 씨앗을 먹는 소형 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '유럽종인 검은머리방울새(Siskin)가 간혹 한국에 출현해 탐조인을 흥분시키는 미조 기록이 됩니다'),

('KR-321', 'ioc14-emb-cir', '흰눈썹멧새', 'Emberiza cirlus', 'Cirl Bunting',
  '참새목', '멧새과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  16,
  '한국에 드물게 출현하는 지중해 계통 멧새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '흰눈썹멧새는 지중해권에 주로 서식하는 종으로 한국 기록은 매우 드문 미조입니다'),

('KR-322', 'ioc14-emb-sch', '쑥새사촌', 'Emberiza schoeniclus', 'Reed Bunting',
  '참새목', '멧새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  15,
  '갈대밭과 습지 주변에서 드물게 월동하는 멧새로 수컷의 검은 머리가 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '쑥새사촌은 한국에서 드물게 기록되는 서유럽-중앙아시아 계통 갈대밭 멧새입니다'),

('KR-323', 'ioc14-emb-tri', '삼색멧새', 'Emberiza tristrami', 'Tristram''s Bunting',
  '참새목', '멧새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  16,
  '산림 가장자리와 덤불에서 드물게 겨울을 나는 멧새로 줄무늬 머리가 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '삼색멧새는 머리에 검은-흰-밤색 세 가지 줄무늬가 선명해 한국 멧새류 중 가장 화려한 두부 패턴을 가집니다'),

('KR-324', 'ioc14-emb-pus', '쑥새류', 'Emberiza pusilla', 'Little Bunting',
  '참새목', '멧새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  13,
  '농경지와 덤불에서 겨울을 나는 소형 멧새로 밤색 뺨과 눈선이 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '소멧새는 한국 겨울 멧새류 중 가장 작은 축에 속하며 참새 무리 속에 섞여 있다가 발견됩니다'),

('KR-325', 'ioc14-pru-mod', '유럽발발이', 'Prunella modularis', 'Dunnock',
  '참새목', '바위종다리과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  15,
  '덤불과 공원 하층에서 드물게 월동하는 참새처럼 보이는 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '유럽발발이는 참새처럼 보이지만 실제로는 전혀 다른 바위종다리과로, 한국에 출현하면 희귀 기록입니다'),

('KR-326', 'ioc14-pru-col', '바위종다리', 'Prunella collaris', 'Alpine Accentor',
  '참새목', '바위종다리과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  18,
  '높은 산 정상부 바위지대에서 서식하며 겨울에 낮은 곳으로 내려오는 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '바위종다리는 고산 바위 사이에서 얼어붙은 틈새 곤충을 찾는 겨울 생존의 달인입니다'),

('KR-327', 'ioc14-cin-cin', '물까마귀', 'Cinclus cinclus', 'White-throated Dipper',
  '참새목', '물까마귀과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  18,
  '맑은 산간 계류에서 잠수해 수서곤충을 먹는 텃새로 흰 가슴이 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '물까마귀는 맑은 계류 속에서 날개로 헤엄치며 바닥을 걸어 다니는 유일한 잠수 참새목 새입니다'),

('KR-328', 'ioc14-par-cin', '개개비사촌', 'Cisticola juncidis', 'Zitting Cisticola',
  '참새목', '개개비사촌과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  10,
  '논, 갈대밭, 풀밭에서 번식하며 위아래로 나는 특이한 비행과 "찍-찍-찍" 소리로 우는 텃새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '개개비사촌은 U자형 위아래 기복 비행을 반복하며 노래해, 날아다니는 메트로놈이라는 별명이 있습니다'),

('KR-329', 'ioc14-loc-lan', '쇠개개비사촌', 'Locustella lanceolata', 'Lanceolated Warbler',
  '참새목', '개개비사촌과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  12,
  '풀밭과 갈대밭을 이동 시 통과하며 긴 풀 사이를 마치 쥐처럼 기어다니는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠개개비사촌은 목격 자체가 어렵고 소리도 낮은 버즈음이어서 탐조 최난이도 종 중 하나입니다'),

('KR-330', 'ioc14-cis-sco', '긴다리개개비', 'Acrocephalus agricola', 'Paddyfield Warbler',
  '참새목', '갈대개개비과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  13,
  '논과 갈대밭을 이동 시 통과하는 나그네새로 긴 눈썹선이 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '긴다리개개비는 서식 환경이 논밭과 갈대밭에 한정되어 한국 농경지 생태계 건강의 지표종으로 쓰입니다'),

('KR-331', 'ioc14-hir-dau', '귀제비', 'Cecropis daurica', 'Red-rumped Swallow',
  '참새목', '제비과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  19,
  '바위 절벽과 건물 처마 밑에 진흙 둥지를 틀고 번식하는 여름철새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '귀제비는 제비와 달리 항아리 모양의 완전히 밀폐된 진흙 둥지를 제작하는 건축 장인입니다'),

('KR-332', 'ioc14-rip-rip', '갈색제비', 'Riparia riparia', 'Sand Martin',
  '참새목', '제비과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  12,
  '강 모래 절벽에 굴을 파고 집단 번식하는 가장 작은 제비',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '갈색제비는 수십 쌍이 강변 모래절벽에 수평 굴을 파고 집단 번식하는 사회적 여름철새입니다'),

('KR-333', 'ioc14-ded-urb', '집제비', 'Delichon urbicum', 'Common House Martin',
  '참새목', '제비과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  13,
  '건물 처마 밑에 진흙 둥지를 지어 번식하는 흰 허리의 제비류',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '집제비는 발에 깃털이 자라 있어 추운 날씨에도 처마에 매달려 있을 수 있는 특수 적응을 가집니다'),

('KR-334', 'ioc14-hir-tat', '흰털발제비', 'Delichon dasypus', 'Asian House Martin',
  '참새목', '제비과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  13,
  '산지 절벽과 건물에서 번식하는 아시아 텃새형 집제비',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '흰털발제비는 집제비와 달리 털이 덜 덮인 발을 가지며 주로 산악 지형의 절벽을 선호합니다'),

('KR-335', 'ioc14-ore-cin', '긴꼬리딱새', 'Terpsiphone paradisi', 'Indian Paradise Flycatcher',
  '참새목', '제왕딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  20,
  '활엽수림과 공원에서 번식하며 수컷의 긴 흰 꼬리 깃이 아름다운 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '긴꼬리딱새 수컷의 흰 꼬리 깃은 몸길이의 두 배로 여름 숲속에서 나풀거리는 흰 리본처럼 보입니다'),

('KR-336', 'ioc14-pho-aur-2', '붉은배지빠귀', 'Ficedula mugimaki', 'Mugimaki Flycatcher',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  13,
  '산지 활엽수림에서 번식하며 수컷의 주황빛 배와 흰 눈썹이 인상적인 여름철새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '붉은배지빠귀 수컷은 초봄 도착 즉시 "삐히리리" 노래를 시작해 산림에 봄 소식을 전합니다'),

('KR-337', 'ioc14-cyn-sue', '쇠유리새', 'Larvivora cyane', 'Siberian Blue Robin',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  14,
  '계곡 주변 울창한 산림 하층에서 번식하며 청색 등이 특징인 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠유리새 수컷의 진한 파란 등은 어두운 숲 속에서도 반짝이며 "숲의 사파이어"로 불립니다'),

('KR-338', 'ioc14-sax-rub', '검은딱새사촌', 'Saxicola rubicola', 'European Stonechat',
  '참새목', '딱새과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  12,
  '농경지와 개활지를 이동 시 드물게 경유하는 유럽 계통 딱새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '검은딱새사촌은 최근 아시아에서 기록이 늘고 있는 유럽 딱새로 한국 발견 시 항상 화제가 됩니다'),

('KR-339', 'ioc14-por-lus', '붉은가슴울새', 'Erithacus rubecula', 'European Robin',
  '참새목', '딱새과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  14,
  '공원과 산림에 드물게 월동하는 유럽 계통 빨간 가슴의 소형 새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '유럽에서 크리스마스 카드의 상징인 붉은가슴울새가 한국에 미조로 나타나면 탐조인들의 발걸음을 모읍니다'),

('KR-340', 'ioc14-mon-fli', '큰덤불해오라기사촌', 'Monticola gularis', 'White-throated Rock Thrush',
  '참새목', '딱새과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  19,
  '산지 암벽 지대에서 번식하며 수컷의 파란 머리와 흰 목이 아름다운 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '흰목바위지빠귀는 암벽 서식 전문가로, 수직 절벽을 자유롭게 이동하며 곤충을 찾습니다'),

('KR-341', 'ioc14-par-pal', '노랑눈썹솔새', 'Phylloscopus inornatus', 'Yellow-browed Warbler',
  '참새목', '솔새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  10,
  '산림을 이동 시 통과하는 노란 눈썹 줄이 선명한 소형 솔새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '노랑눈썹솔새는 화려한 노란 눈썹 줄 덕에 비슷한 솔새들 중 가장 쉽게 동정되는 친절한 나그네새입니다'),

('KR-342', 'ioc14-syl-nin', '긴꼬리솔새', 'Phylloscopus schwarzi', 'Radde''s Warbler',
  '참새목', '솔새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  12,
  '낙엽수림 하층 덤불을 이동 시 통과하는 나그네새로 굵은 눈썹선이 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '래디스솔새는 통통하고 느린 움직임으로 다른 솔새와 달리 덤불 속을 천천히 기어다닙니다'),

('KR-343', 'ioc14-syl-dul', '긴꼬리딱새사촌', 'Muscicapa ferruginea', 'Ferruginous Flycatcher',
  '참새목', '딱새과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  13,
  '산지 활엽수림에서 드물게 번식하며 붉은빛 옆구리가 특징인 소형 딱새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '무당딱새로도 불리는 이 새는 제주도와 내륙 일부 지역에서만 번식이 확인된 희귀 여름철새입니다'),

('KR-344', 'ioc14-lus-cal', '검은머리방울새', 'Spinus spinus', 'Eurasian Siskin',
  '참새목', '되새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  11,
  '침엽수림과 오리나무 군락에서 겨울을 나며 씨앗을 먹는 소형 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '검은머리방울새는 오리나무 씨앗을 탐색하며 매달려 거꾸로 먹는 곡예 섭식으로 유명합니다'),

('KR-345', 'ioc14-car-fla', '홍방울새', 'Acanthis flammea', 'Common Redpoll',
  '참새목', '되새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  13,
  '자작나무 숲과 공원에서 드물게 겨울을 나며 이마의 붉은 반점이 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '홍방울새는 불규칙하게 대량 남하하는 해가 있으며, 이런 해에 자작나무 군락에서 수십 마리를 볼 수 있습니다'),

('KR-346', 'ioc14-emb-yese', '붉은멧새', 'Emberiza elegans yessoensis', 'Yellow-throated Bunting (Yesso)',
  '참새목', '멧새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  16,
  '산림과 공원에서 번식하며 수컷의 황금빛 노란 목이 선명한 여름철새 아종',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '노랑턱멧새 예소아종은 제주도와 남부 도서에서 번식하는 아종으로 독립종 검토가 진행 중입니다'),

('KR-347', 'ioc14-syl-cur', '쇠흰뺨새', 'Curruca curruca', 'Lesser Whitethroat',
  '참새목', '솔새과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  14,
  '덤불 지역을 드물게 이동 시 통과하는 유럽 계통 솔새류의 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠흰뺨새는 유럽-중앙아시아 계통의 솔새과 새로 한국 기록은 극히 드문 미조입니다'),

('KR-348', 'ioc14-lus-meg', '큰유리딱새', 'Luscinia megarhynchos', 'Common Nightingale',
  '참새목', '딱새과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  16,
  '유럽 계통의 나이팅게일로 한국에 드물게 출현하는 미조',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '나이팅게일은 문학과 시에서 가장 많이 찬양받은 새로, 한국 기록은 동양에 나타난 기적적인 미조입니다'),

('KR-349', 'ioc14-tur-vis', '개똥지빠귀사촌', 'Turdus viscivorus', 'Mistle Thrush',
  '참새목', '지빠귀과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  27,
  '유럽 계통의 대형 지빠귀로 한국에 드물게 출현하는 미조',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '겨우살이 열매를 즐겨 먹어 "Mistle Thrush"라 불리며 한국 출현 시 희귀 보고로 기록됩니다'),

('KR-350', 'ioc14-phy-pro', '봄솔새', 'Phylloscopus proregulus', 'Pallas''s Leaf Warbler',
  '참새목', '솔새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  9,
  '침엽수림을 이동 시 통과하는 초소형 솔새로 노란 허리가 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '봄솔새는 솔새류 중 가장 작은 편으로 나뭇잎 밑면에 매달려 먹이를 찾는 곤충 같은 소형 조류입니다');

COMMIT;

-- DOWN
BEGIN;
DELETE FROM species WHERE species_id IN (
  'KR-286','KR-287','KR-288','KR-289','KR-290','KR-291','KR-292','KR-293',
  'KR-294','KR-295','KR-296','KR-297','KR-298','KR-299','KR-300','KR-301',
  'KR-302','KR-303','KR-304','KR-305','KR-306','KR-307','KR-308','KR-309',
  'KR-310','KR-311','KR-312','KR-313','KR-314','KR-315','KR-316','KR-317',
  'KR-318','KR-319','KR-320','KR-321','KR-322','KR-323','KR-324','KR-325',
  'KR-326','KR-327','KR-328','KR-329','KR-330','KR-331','KR-332','KR-333',
  'KR-334','KR-335','KR-336','KR-337','KR-338','KR-339','KR-340','KR-341',
  'KR-342','KR-343','KR-344','KR-345','KR-346','KR-347','KR-348','KR-349',
  'KR-350'
);
COMMIT;
