-- Migration: 조류 종 시드 데이터 Batch 3 (65종) — 맹금류 + 산림조류
-- Date: 2026-04-04
-- Description: 천연기념물 1종 + 희귀종 10종 + 나그네새 27종 + 텃새 27종
-- Source: IOC World Bird List v14.x, NIBR 한국 조류 체크리스트, 문화재청 천연기념물 목록
-- Depends: 20260404_000001_create_species_table.sql

-- UP
BEGIN;

-- ============================================================
-- SECTION 1: 천연기념물 (Legendary) — sensitivity_tier=1, points=25
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-161', 'ioc14-dry-jav', '크낙새', 'Dryocopus javensis', 'White-bellied Woodpecker',
  '딱따구리목', '딱따구리과', 'legendary', 1, 25,
  5, TRUE, '제197호', 'LC',
  48,
  '오래된 낙엽활엽수림의 고목에서만 서식하며 한국에서는 사실상 절멸 위기에 처해 있다',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '크낙새는 한국에서 마지막으로 관찰된 지 수십 년이 지났으며, 한반도 고유 아종의 생사가 불분명한 전설적인 새입니다');

-- ============================================================
-- SECTION 2: 희귀종 (Rare) — points=10, is_locked_free=TRUE
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-162', 'ioc14-aqu-cla', '흑수리', 'Clanga clanga', 'Greater Spotted Eagle',
  '수리목', '수리과', 'rare', 2, 10,
  3, TRUE, NULL, 'VU',
  65,
  '넓은 산지와 하구 습지에 드물게 월동하며 중형 포유류와 조류를 사냥한다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '흑수리는 어린 개체에서 성조까지 깃털 색이 수년에 걸쳐 변하는 긴 성장 과정을 거칩니다'),

('KR-163', 'ioc14-pan-hal', '물수리', 'Pandion haliaetus', 'Osprey',
  '수리목', '물수리과', 'rare', 3, 10,
  2, TRUE, NULL, 'LC',
  60,
  '강과 해안을 이동 시 경유하며 발로 물고기를 낚아채는 전문 어획 맹금류',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '물수리는 발가락에 역방향으로 회전하는 특수 관절이 있어 미끄러운 물고기를 앞발가락 2개로 단단히 쥡니다'),

('KR-164', 'ioc14-mil-mig', '솔개', 'Milvus migrans', 'Black Kite',
  '수리목', '수리과', 'rare', 3, 10,
  2, TRUE, NULL, 'LC',
  55,
  '한국에서 번식 개체군이 감소 중인 대형 맹금류로 포크형 꼬리가 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '솔개는 열 기류를 타고 날갯짓 없이 수 시간을 비행할 수 있는 에너지 효율의 달인입니다'),

('KR-165', 'ioc14-acc-gen', '참매', 'Accipiter gentilis', 'Northern Goshawk',
  '수리목', '수리과', 'rare', 3, 10,
  2, TRUE, NULL, 'LC',
  55,
  '깊은 산지의 오래된 숲에서 번식하며 빠른 속도로 숲 속을 날아 조류를 사냥한다',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '참매는 매사냥에 가장 많이 쓰인 전통 사냥새로, 고려시대부터 왕실에서 귀중히 여겼습니다'),

('KR-166', 'ioc14-str-ura', '올빼미', 'Strix uralensis', 'Ural Owl',
  '올빼미목', '올빼미과', 'rare', 3, 10,
  2, TRUE, NULL, 'LC',
  60,
  '깊은 산림에서 서식하는 대형 올빼미로 고목의 구멍에 둥지를 틀고 야간 사냥을 한다',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '올빼미는 머리를 270도까지 회전시켜 소리의 방향을 삼차원으로 정확하게 파악합니다'),

('KR-167', 'ioc14-col-jou', '흑비둘기', 'Columba jouyi', 'Ryukyu Woodpigeon',
  '비둘기목', '비둘기과', 'rare', 2, 10,
  4, TRUE, NULL, 'CR',
  40,
  '제주도 상록수림에 극소수가 서식하는 것으로 추정되나 현황이 불분명한 CR 등급 종',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '흑비둘기는 오키나와에서는 이미 절멸했으며 제주도 마지막 개체군의 생존 여부가 초미의 관심사입니다'),

('KR-168', 'ioc14-cla-cla', '아무르매', 'Falco amurensis', 'Amur Falcon',
  '매목', '매과', 'rare', 3, 10,
  3, TRUE, NULL, 'LC',
  30,
  '봄가을 이동 시 한국을 경유하며 곤충을 주로 먹는 소형 매',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '아무르매는 아프리카까지 수만 킬로미터를 이동하는 장거리 철새이며 집단으로 인도양을 건넙니다'),

('KR-169', 'ioc14-hal-leu', '흰배바다수리', 'Haliaeetus leucogaster', 'White-bellied Sea Eagle',
  '수리목', '수리과', 'rare', 2, 10,
  4, TRUE, NULL, 'LC',
  80,
  '남해안과 제주도 해안에 드물게 출현하는 열대·아열대 수리',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":false,"sep":true,"oct":true,"nov":false,"dec":false}',
  '흰배바다수리는 한국에서 보기 드문 미조로, 기후 변화로 북방 출현 빈도가 조금씩 늘고 있습니다'),

('KR-170', 'ioc14-nix-jap', '솔부엉이', 'Ninox japonica', 'Northern Boobook',
  '올빼미목', '올빼미과', 'rare', 3, 10,
  3, TRUE, NULL, 'LC',
  30,
  '평지에서 산지까지 다양한 숲에서 번식하는 여름철새로 야간에 곤충과 소형 척추동물을 사냥한다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '솔부엉이는 작은 몸에 노란 눈이 인상적이며 "부엉-부엉" 반복 울음이 여름밤 산림의 대표 소리입니다'),

('KR-171', 'ioc14-dry-mar', '까막딱따구리', 'Dryocopus martius', 'Black Woodpecker',
  '딱따구리목', '딱따구리과', 'rare', 3, 10,
  2, TRUE, NULL, 'LC',
  45,
  '오래된 침엽수 및 혼효림에 서식하며 고목에 큰 구멍을 파고 번식하는 대형 딱따구리',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '까막딱따구리가 파는 큰 수동은 이후 소쩍새나 원앙의 둥지로 재활용되는 숲의 집짓기 봉사입니다');

-- ============================================================
-- SECTION 3: 나그네새/겨울·여름철새 (Migrant) — sensitivity_tier=3, points=3
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-172', 'ioc14-fal-sub', '새호리기', 'Falco subbuteo', 'Eurasian Hobby',
  '매목', '매과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  33,
  '평지와 산림 가장자리를 이동 시 통과하며 곤충과 소형 조류를 잡는 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '새호리기는 비행 중 잡은 먹이를 공중에서 발로 들어 부리로 먹는 곡예 비행을 합니다'),

('KR-173', 'ioc14-acc-sol', '비둘기조롱이', 'Accipiter soloensis', 'Chinese Sparrowhawk',
  '수리목', '수리과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  33,
  '평지 숲과 산림에서 봄가을 이동 시 통과하며 개구리와 소형 파충류를 먹는다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '비둘기조롱이는 가슴의 주황빛 바탕에 세로 줄무늬가 없어 다른 조롱이류와 구별됩니다'),

('KR-174', 'ioc14-acc-gul', '조롱이', 'Accipiter gularis', 'Japanese Sparrowhawk',
  '수리목', '수리과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  27,
  '산림과 평지를 이동 시 통과하는 소형 맹금류로 소형 조류를 빠르게 사냥한다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '조롱이는 수컷이 암컷보다 훨씬 작아 같은 종의 암수가 전혀 다른 새처럼 보이는 극단적인 성이형을 보입니다'),

('KR-175', 'ioc14-acc-nis', '새매', 'Accipiter nisus', 'Eurasian Sparrowhawk',
  '수리목', '수리과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  33,
  '도시 공원부터 산림까지 어디서나 월동하며 소형 조류를 빠른 비행으로 잡는다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '새매 암컷은 수컷보다 무게가 두 배로 커서, 수컷이 잡지 못하는 멧비둘기까지 사냥할 수 있습니다'),

('KR-176', 'ioc14-but-jap', '말똥가리', 'Buteo japonicus', 'Eastern Buzzard',
  '수리목', '수리과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  52,
  '농경지, 구릉지, 하구 습지에서 월동하며 들쥐와 개구리를 잡는 흔한 겨울 맹금류',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '말똥가리는 전봇대와 고목에 앉아 장시간 기다리다 날카로운 눈으로 들쥐를 발견하면 내려꽂습니다'),

('KR-177', 'ioc14-but-hem', '큰말똥가리', 'Buteo hemilasius', 'Upland Buzzard',
  '수리목', '수리과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  65,
  '개활지와 농경지에서 드물게 월동하며 말똥가리보다 체형이 크고 색 변이가 다양하다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '큰말똥가리는 흰색형·갈색형·중간형 등 깃털 색 변이가 많아 현장 동정이 어렵습니다'),

('KR-178', 'ioc14-asi-fla', '쇠부엉이', 'Asio flammeus', 'Short-eared Owl',
  '올빼미목', '올빼미과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  38,
  '농경지와 갯벌 주변 개활지에서 월동하며 낮에도 활동하는 특이한 올빼미',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '쇠부엉이는 올빼미류 중 드물게 낮에 사냥하며, 갯벌 위를 낮게 나는 독특한 비행으로 구분됩니다'),

('KR-179', 'ioc14-asi-otu', '칡부엉이', 'Asio otus', 'Long-eared Owl',
  '올빼미목', '올빼미과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  36,
  '산림과 농경지 경계 지역에서 월동하며 낮에는 나무에 붙어 위장하고 야간에 사냥한다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '칡부엉이의 귀 모양 깃은 실제 귀가 아니라 감정 표현용으로, 위협받으면 세워 더 크게 보입니다'),

('KR-180', 'ioc14-otu-sun', '소쩍새', 'Otus sunia', 'Oriental Scops Owl',
  '올빼미목', '올빼미과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  19,
  '평지에서 산지까지 다양한 숲에서 번식하는 소형 여름 올빼미로 야간에 곤충을 먹는다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '"소쩍-소쩍" 울음으로 유명한 소쩍새는 예로부터 흉조로 여겨졌으나 실제로는 해충을 잡는 이로운 새입니다'),

('KR-181', 'ioc14-jun-tor', '개미잡이', 'Jynx torquilla', 'Eurasian Wryneck',
  '딱따구리목', '딱따구리과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  16,
  '농경지와 숲 가장자리를 이동 시 경유하며 개미와 애벌레를 긴 혀로 잡는 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '개미잡이는 위협받으면 뱀처럼 목을 비틀고 쉬쉬 소리를 내어 포식자를 혼란에 빠뜨립니다'),

('KR-182', 'ioc14-eur-ori', '파랑새', 'Eurystomus orientalis', 'Oriental Dollarbird',
  '파랑새목', '파랑새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  30,
  '산림 가장자리 큰 나무에서 번식하며 비행 중 곤충을 잡는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '파랑새는 앉아 있을 때 초록빛이 도는 파란색이지만 비행 중에는 날개의 파란 원이 반짝입니다'),

('KR-183', 'ioc14-upu-epo', '후투티', 'Upupa epops', 'Eurasian Hoopoe',
  '파랑새목', '후투티과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  28,
  '농경지, 과수원, 공원을 이동 시 통과하며 땅을 파 유충을 먹는 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '후투티는 위협받으면 화려한 댕기를 활짝 펼쳐 눈 모양 무늬를 드러내 포식자를 위협합니다'),

('KR-184', 'ioc14-apu-apu', '칼새', 'Apus apus', 'Common Swift',
  '칼새목', '칼새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  17,
  '도심 건물 틈새와 절벽에서 번식하며 비행 중 곤충만 잡는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '칼새는 먹고 자고 심지어 짝짓기까지 공중에서 하며, 일생의 99%를 비행으로 보냅니다'),

('KR-185', 'ioc14-hir-cau', '바늘꼬리칼새', 'Hirundapus caudacutus', 'White-throated Needletail',
  '칼새목', '칼새과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  21,
  '산악 지역과 해안을 이동 시 통과하며 빠른 속도로 곤충을 잡는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '바늘꼬리칼새는 수평 비행 속도가 시속 169km에 달해 새 중 가장 빠른 수평 비행 기록 보유자입니다'),

('KR-186', 'ioc14-cap-jot', '쏙독새', 'Caprimulgus jotaka', 'Gray Nightjar',
  '쏙독새목', '쏙독새과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  28,
  '산림 가장자리와 개활 초지에서 번식하며 야간에 날아다니는 곤충을 잡는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쏙독새는 땅 위에서 나뭇잎처럼 위장해 낮에 잠을 자며, 눈을 뜨지 않으면 발견이 거의 불가능합니다'),

('KR-187', 'ioc14-pic-can', '청딱따구리', 'Picus canus', 'Grey-headed Woodpecker',
  '딱따구리목', '딱따구리과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  30,
  '산림과 도시 공원에서 서식하며 나무 속 개미를 긴 혀로 핥아 먹는 텃새형 철새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '청딱따구리의 혀는 머리뼈 둘레를 감싸는 긴 설골에 연결되어 부리보다 6cm 더 나올 수 있습니다'),

('KR-188', 'ioc14-den-leu', '큰오색딱따구리', 'Dendrocopos leucotos', 'White-backed Woodpecker',
  '딱따구리목', '딱따구리과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  27,
  '오래된 낙엽활엽수림에서 서식하며 썩은 고목의 딱정벌레 애벌레를 파내 먹는다',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '큰오색딱따구리는 오래된 숲의 건강 지표 종으로, 이 새가 사는 숲은 생태적으로 우량한 숲입니다'),

('KR-189', 'ioc14-col-rup', '양비둘기', 'Columba rupestris', 'Hill Pigeon',
  '비둘기목', '비둘기과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  33,
  '석회암 절벽과 산지 암벽에서 번식하며 씨앗과 곡류를 먹는 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '양비둘기는 도심 집비둘기의 조상인 바위비둘기(Columbia livia)와 유사하나 허리가 흰빛이 도는 특징이 있습니다'),

('KR-190', 'ioc14-cuc-mic', '두견이', 'Cuculus micropterus', 'Indian Cuckoo',
  '뻐꾸기목', '뻐꾸기과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  32,
  '울창한 활엽수림에서 번식하며 "한잔 더-한잔 더" 우는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":false,"oct":false,"nov":false,"dec":false}',
  '두견이의 4음절 울음소리는 예로부터 이별과 그리움을 상징해 한국 시가에 자주 등장합니다'),

('KR-191', 'ioc14-cuc-sat', '벙어리뻐꾸기', 'Cuculus optatus', 'Oriental Cuckoo',
  '뻐꾸기목', '뻐꾸기과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  32,
  '산지 활엽수림과 침엽수림에서 번식하며 "두-두-두-두" 반복 울음을 내는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":false,"oct":false,"nov":false,"dec":false}',
  '벙어리뻐꾸기는 뻐꾸기와 달리 "뻐꾸기" 소리가 아닌 저음의 반복 소리를 내어 구별됩니다'),

('KR-192', 'ioc14-fal-col', '비둘기매', 'Falco columbarius', 'Merlin',
  '매목', '매과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  30,
  '개활지와 해안을 이동 시 경유하며 소형 조류와 곤충을 잡는 소형 매',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '비둘기매는 소형 맹금류 중 가장 빠른 수평 비행을 하며 먹이를 뒤에서 추격해 잡습니다'),

('KR-193', 'ioc14-but-but', '유라시아말똥가리', 'Buteo buteo', 'Common Buzzard',
  '수리목', '수리과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  55,
  '농경지와 개활 산지에서 드물게 월동하며 말똥가리와 혼서하는 경우가 있다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '유라시아말똥가리는 색 변이가 매우 다양해 같은 종끼리도 외모가 크게 달라 보이는 경우가 흔합니다'),

('KR-194', 'ioc14-cuc-can-2', '매사촌', 'Hierococcyx sparverioides', 'Large Hawk-Cuckoo',
  '뻐꾸기목', '뻐꾸기과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  38,
  '산지 활엽수림에서 번식하는 여름철새로 생김새가 매와 비슷해 포식자를 흉내낸다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":false,"oct":false,"nov":false,"dec":false}',
  '매사촌은 매와 비슷한 외모로 소형 새들을 놀라게 해 그 틈에 탁란할 숙주 둥지에 접근합니다'),

('KR-195', 'ioc14-cir-spi', '개구리매', 'Circus spilonotus', 'Eastern Marsh Harrier',
  '수리목', '수리과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  50,
  '농경지, 습지, 갈대밭을 낮게 날며 개구리·들쥐·소형 조류를 사냥하는 나그네새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '개구리매는 갈대밭 위를 느리게 날다 급강하하는 독특한 사냥법으로 개구리를 포획합니다');

-- ============================================================
-- SECTION 4: 텃새 (Common) — sensitivity_tier=3, points=1
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-196', 'ioc14-den-maj', '오색딱따구리', 'Dendrocopos major', 'Great Spotted Woodpecker',
  '딱따구리목', '딱따구리과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  23,
  '도시 공원부터 깊은 산림까지 어디서나 볼 수 있는 한국의 가장 흔한 딱따구리',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '오색딱따구리는 초당 20회 나무를 쪼을 때 뇌 진탕 없이 충격을 흡수하는 특수 두개골을 가집니다'),

('KR-197', 'ioc14-yun-kiz', '쇠딱따구리', 'Yungipicus kizuki', 'Japanese Pygmy Woodpecker',
  '딱따구리목', '딱따구리과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  15,
  '산림과 도시 공원의 작은 나무에서 서식하는 한국에서 가장 작은 딱따구리',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '쇠딱따구리는 참새 크기이지만 정교하게 나무를 쪼아 작은 벌레 굴까지 찾아내는 능력을 가집니다'),

('KR-198', 'ioc14-str-ori-2', '콩새', 'Coccothraustes coccothraustes', 'Hawfinch',
  '참새목', '되새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  18,
  '활엽수림과 과수원에서 겨울을 나며 씨앗과 열매를 굵은 부리로 쪼아 먹는다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '콩새의 부리는 버찌 씨앗을 깨는 데 70kg에 달하는 힘을 발휘할 수 있습니다'),

('KR-199', 'ioc14-stu-uni', '찌르레기', 'Spodiopsar cineraceus', 'White-cheeked Starling',
  '참새목', '찌르레기과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  24,
  '농경지, 과수원, 공원에서 번식하며 무리지어 이동하는 여름철새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '찌르레기는 구멍이 있는 나무나 전봇대 틈새에 집을 짓고, 때로는 참새의 둥지를 강탈하기도 합니다'),

('KR-200', 'ioc14-tur-man', '검은지빠귀', 'Turdus mandarinus', 'Chinese Blackbird',
  '참새목', '지빠귀과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  28,
  '산림 하층과 공원 덤불에서 서식하며 지렁이와 열매를 먹는 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '검은지빠귀 수컷의 풍부한 노래 레퍼토리는 수십 가지 음절을 자유롭게 조합한 즉흥 연주입니다'),

('KR-201', 'ioc14-tur-pal-2', '개똥지빠귀', 'Turdus eunomus', 'Dusky Thrush',
  '참새목', '지빠귀과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  24,
  '평지와 산지 숲, 농경지에서 무리지어 월동하며 나무 열매와 지렁이를 먹는다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '개똥지빠귀는 한국에서 "똥새"라는 다소 친근한 별명으로 불리며 겨울 들판에서 흔히 볼 수 있습니다'),

('KR-202', 'ioc14-sax-mau', '검은딱새', 'Saxicola maurus', 'Siberian Stonechat',
  '참새목', '딱새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  13,
  '농경지, 개활지, 산림 가장자리에서 나그네새로 지나가며 곤충을 잡아먹는다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '검은딱새 수컷은 높은 곳에 앉아 꼬리를 빠르게 흔들며 영역을 표시하는 "공중 깃발" 행동을 합니다'),

('KR-203', 'ioc14-mon-sol', '바다직박구리', 'Monticola solitarius', 'Blue Rock Thrush',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  23,
  '해안 절벽, 바위 해안, 등대에서 서식하며 파란 수컷이 바위 위에서 노래하는 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '바다직박구리 수컷의 파란 깃털은 구조색으로, 젖거나 각도에 따라 녹색 또는 회색으로 보입니다'),

('KR-204', 'ioc14-lus-sib', '울새', 'Luscinia sibilans', 'Rufous-tailed Robin',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  14,
  '낙엽수림 바닥층을 이동 시 경유하며 지렁이와 곤충을 먹는 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '울새는 주황빛 꼬리를 빠르게 흔들며 걷는 독특한 행동으로 바닥에서 쉽게 알아볼 수 있습니다'),

('KR-205', 'ioc14-tar-cya', '유리딱새', 'Tarsiger cyanurus', 'Red-flanked Bluetail',
  '참새목', '딱새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  14,
  '산림과 덤불 지역을 이동 시 경유하는 나그네새로 꼬리 옆구리의 파란빛이 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '유리딱새 수컷의 파란 꼬리 측면은 가을 이동 때 한국 산림에서 가장 아름다운 작은 새 중 하나입니다'),

('KR-206', 'ioc14-fic-nar', '황금새', 'Ficedula narcissina', 'Narcissus Flycatcher',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  13,
  '낙엽수림과 혼효림을 이동 시 경유하며 나뭇잎 사이 곤충을 잡는 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '황금새 수컷의 선명한 노랑-검정 색 대비는 동아시아 소형 조류 중 가장 화려한 배색으로 꼽힙니다'),

('KR-207', 'ioc14-cya-cya', '큰유리새', 'Cyanoptila cyanomelana', 'Blue-and-white Flycatcher',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  17,
  '산림에서 번식하며 파란 등과 흰 배의 선명한 대비가 특징인 여름철새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '큰유리새 수컷의 맑고 풍부한 노랫소리는 한국 산림에서 가장 아름다운 노래 중 하나로 손꼽힙니다'),

('KR-208', 'ioc14-mus-gri', '솔딱새', 'Muscicapa griseisticta', 'Grey-streaked Flycatcher',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  15,
  '산림 가장자리와 공원에서 공중 포충하며 이동하는 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '솔딱새는 나뭇가지에서 곤충을 향해 정확하게 날아가 잡은 후 항상 같은 자리로 돌아오는 습성이 있습니다'),

('KR-209', 'ioc14-mus-sib', '쇠솔딱새', 'Muscicapa sibirica', 'Dark-sided Flycatcher',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  13,
  '산림에서 번식하며 이동 시 공원 나무에서도 관찰되는 소형 딱새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠솔딱새는 어두운 갈색빛 외모와 달리 민첩한 비행으로 공중의 곤충을 정확하게 포획합니다'),

('KR-210', 'ioc14-pho-och', '흰눈썹딱새', 'Ficedula albicilla', 'Taiga Flycatcher',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  12,
  '산림과 덤불을 이동 시 경유하는 나그네새로 흰 눈썹 줄이 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '흰눈썹딱새는 꼬리를 위아래로 흔드는 독특한 행동으로 같은 서식지의 유사종과 구별됩니다'),

('KR-211', 'ioc14-reg-reg', '상모솔새', 'Regulus regulus', 'Goldcrest',
  '참새목', '상모솔새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  9,
  '침엽수림을 이동 시 경유하거나 겨울을 나며 나뭇잎 사이 작은 곤충을 먹는 최소형 새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '상모솔새는 몸무게 6g으로 한국에서 가장 작은 새이지만 시베리아에서까지 날아오는 강인한 철새입니다'),

('KR-212', 'ioc14-tro-tro', '굴뚝새', 'Troglodytes troglodytes', 'Eurasian Wren',
  '참새목', '굴뚝새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  10,
  '바위 틈새와 덤불 아래 지면 가까이 살며 큰 소리로 노래하는 소형 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '굴뚝새는 몸 크기 대비 노래 크기가 가장 큰 새로, 체중의 10배에 해당하는 볼륨으로 노래합니다'),

('KR-213', 'ioc14-sit-eur', '동고비', 'Sitta europaea', 'Eurasian Nuthatch',
  '참새목', '동고비과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  14,
  '활엽수림과 공원에서 나무 줄기를 오르내리며 곤충과 씨앗을 먹는 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '동고비는 발로 나무를 쥐고 머리를 아래로 향해 수직 하강하는 세계에서 몇 안 되는 조류입니다'),

('KR-214', 'ioc14-cuc-can-3', '두견이사촌', 'Cuculus poliocephalus', 'Lesser Cuckoo',
  '뻐꾸기목', '뻐꾸기과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  26,
  '산지 활엽수림에서 번식하며 "빽빽빽" 소리로 울어 뻐꾸기와 구별되는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":false,"oct":false,"nov":false,"dec":false}',
  '두견이사촌은 스스로 둥지를 짓지 않고 뱁새 등 소형 조류의 둥지에 알을 낳는 탁란종입니다'),

('KR-215', 'ioc14-tur-nau', '노랑지빠귀', 'Turdus naumanni', 'Naumann''s Thrush',
  '참새목', '지빠귀과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  24,
  '농경지와 공원에서 개똥지빠귀와 함께 겨울을 나며 나무 열매를 먹는다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '노랑지빠귀와 개똥지빠귀는 오랫동안 같은 종의 아종으로 분류됐으나 현재는 별개 종으로 인정됩니다'),

('KR-216', 'ioc14-tur-obs', '흰눈썹지빠귀', 'Turdus obscurus', 'Eyebrowed Thrush',
  '참새목', '지빠귀과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  23,
  '산림과 공원을 이동 시 경유하는 나그네새로 흰 눈썹 줄이 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '흰눈썹지빠귀는 이동 중 과실수 열매를 대량 먹으며 씨앗을 멀리 퍼뜨리는 산림 복원 기여자입니다'),

('KR-217', 'ioc14-tur-hor', '되지빠귀', 'Turdus hortulorum', 'Grey-backed Thrush',
  '참새목', '지빠귀과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  23,
  '산지 혼효림에서 번식하는 여름철새로 회색 등과 주황빛 가슴이 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '되지빠귀는 새벽 일찍 우는 새 중 하나로, 동트기 전부터 풍부한 노래를 쏟아냅니다'),

('KR-218', 'ioc14-tur-aur', '호랑지빠귀', 'Zoothera aurea', 'White''s Thrush',
  '참새목', '지빠귀과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  30,
  '산지 낙엽수림 아래 축축한 사면을 이동 시 통과하며 지렁이와 열매를 먹는다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '호랑지빠귀의 비늘 무늬 깃털은 낙엽 위에서 완벽한 보호색이 되어 관찰하기 매우 어렵습니다'),

('KR-219', 'ioc14-lus-svi', '진홍가슴', 'Luscinia svecica', 'Bluethroat',
  '참새목', '딱새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  14,
  '수초 습지와 갈대밭 주변을 이동 시 경유하는 나그네새로 파란 목이 수컷의 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '진홍가슴 수컷의 파란 목 중앙에는 밤색 또는 흰 반점이 있어 지역마다 색이 다른 "목 문신"을 가집니다'),

('KR-220', 'ioc14-poe-pal', '쇠박새', 'Poecile palustris', 'Marsh Tit',
  '참새목', '박새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  12,
  '낙엽수림과 혼효림에서 서식하며 씨앗과 벌레를 먹는 소형 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '쇠박새는 겨울에 먹이를 여러 장소에 분산 저장하고 달 단위로 기억해내는 정교한 공간 기억력을 가집니다'),

('KR-221', 'ioc14-per-ate', '진박새', 'Periparus ater', 'Coal Tit',
  '참새목', '박새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  11,
  '침엽수림에서 서식하며 솔방울 씨앗을 파내 먹는 소형 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '진박새는 솔방울 비늘 틈새에 정확히 부리를 넣어 씨앗을 꺼내는 숙련된 "씨앗 채취사"입니다'),

('KR-222', 'ioc14-poe-mon', '북방쇠박새', 'Poecile montanus', 'Willow Tit',
  '참새목', '박새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  13,
  '혼효림에서 서식하며 스스로 고목을 파서 둥지 구멍을 만드는 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '북방쇠박새는 박새과 중 유일하게 스스로 나무를 파서 둥지 구멍을 만드는 종입니다'),

('KR-223', 'ioc14-zos-jap', '뱁새(동박새)', 'Zosterops japonicus', 'Japanese White-eye',
  '참새목', '동박새과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  11,
  '남해안 도서와 제주도의 상록수림에서 서식하며 꽃꿀과 과실을 먹는 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '동박새는 눈 주위 흰 테두리가 안경처럼 보여 영어로 "White-eye"로 불리는 귀여운 소형 텃새입니다'),

('KR-224', 'ioc14-aeg-cau-2', '붉은부리찌르레기', 'Agropsar philippensis', 'Chestnut-cheeked Starling',
  '참새목', '찌르레기과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  19,
  '산림과 과수원을 이동 시 경유하는 나그네새로 수컷의 밤색 뺨이 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '붉은부리찌르레기는 이동 시 수백 마리가 함께 비행하며 복잡한 군무를 연출합니다'),

('KR-225', 'ioc14-cin-cya', '청박새', 'Cyanistes cyanus', 'Azure Tit',
  '참새목', '박새과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  12,
  '겨울에 드물게 내려오는 박새과 조류로 청록빛 깃털이 특징인 희귀 겨울철새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '청박새는 한반도에서 불규칙하게 출현하는 희귀 겨울철새로 박새과에서 가장 파란빛이 도는 종입니다');

COMMIT;

-- DOWN
BEGIN;
DELETE FROM species WHERE species_id IN (
  'KR-161','KR-162','KR-163','KR-164','KR-165','KR-166','KR-167','KR-168',
  'KR-169','KR-170','KR-171','KR-172','KR-173','KR-174','KR-175','KR-176',
  'KR-177','KR-178','KR-179','KR-180','KR-181','KR-182','KR-183','KR-184',
  'KR-185','KR-186','KR-187','KR-188','KR-189','KR-190','KR-191','KR-192',
  'KR-193','KR-194','KR-195','KR-196','KR-197','KR-198','KR-199','KR-200',
  'KR-201','KR-202','KR-203','KR-204','KR-205','KR-206','KR-207','KR-208',
  'KR-209','KR-210','KR-211','KR-212','KR-213','KR-214','KR-215','KR-216',
  'KR-217','KR-218','KR-219','KR-220','KR-221','KR-222','KR-223','KR-224',
  'KR-225'
);
COMMIT;
