-- Migration: 조류 종 시드 데이터 Batch 4 (60종) — 도요·물떼새·갈매기류
-- Date: 2026-04-04
-- Description: 희귀종 6종 + 나그네새 37종 + 텃새 17종
-- Source: IOC World Bird List v14.x, NIBR 한국 조류 체크리스트
-- Depends: 20260404_000001_create_species_table.sql

-- UP
BEGIN;

-- ============================================================
-- SECTION 1: 희귀종 (Rare) — points=10, is_locked_free=TRUE
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-226', 'ioc14-lim-sem', '긴발톱도요', 'Calidris ferruginea', 'Curlew Sandpiper',
  '도요목', '도요과', 'rare', 3, 10,
  3, TRUE, NULL, 'NT',
  21,
  '갯벌과 조간대에서 굽은 부리로 갯지렁이를 깊이 파내는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":false,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '긴발톱도요는 북극에서 호주까지 편도 1만2천km를 단번에 날아가는 장거리 이동 챔피언입니다'),

('KR-227', 'ioc14-lim-pla', '큰뒷부리도요', 'Limosa lapponica', 'Bar-tailed Godwit',
  '도요목', '도요과', 'rare', 3, 10,
  3, TRUE, NULL, 'NT',
  38,
  '서해안 갯벌과 조간대에서 긴 부리로 갯지렁이를 파내는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '큰뒷부리도요는 알래스카에서 뉴질랜드까지 11,000km를 11일 동안 쉬지 않고 나는 세계 최장 무착륙 비행 기록 보유자입니다'),

('KR-228', 'ioc14-cal-can', '붉은가슴도요', 'Calidris canutus', 'Red Knot',
  '도요목', '도요과', 'rare', 2, 10,
  3, TRUE, NULL, 'NT',
  24,
  '서해안 갯벌에 집결해 조개와 갯지렁이를 대량 섭취하는 중요한 경유 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":false,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '붉은가슴도요의 경유지 갯벌 소실이 개체군 급감의 주범으로, 한국 갯벌이 핵심 중간 기착지입니다'),

('KR-229', 'ioc14-ste-par', '도둑갈매기', 'Stercorarius parasiticus', 'Parasitic Jaeger',
  '도요목', '도둑갈매기과', 'rare', 3, 10,
  3, TRUE, NULL, 'LC',
  46,
  '해안 해역을 통과하는 나그네새로 다른 바닷새에게서 먹이를 빼앗는 해적 행동으로 유명하다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '도둑갈매기는 다른 새가 물고기를 잡는 즉시 공중에서 쫓아가 떨어뜨리게 하여 빼앗는 영리한 전략을 씁니다'),

('KR-230', 'ioc14-lim-lim', '큰도요', 'Limosa limosa', 'Black-tailed Godwit',
  '도요목', '도요과', 'rare', 2, 10,
  3, TRUE, NULL, 'NT',
  42,
  '갯벌과 논에서 무릎까지 물에 들어가 긴 부리로 먹이를 탐색하는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '큰도요는 번식지에서 봄까지 먹는 것에만 집중해 체중을 두 배로 늘린 뒤 장거리 이동을 떠납니다'),

('KR-231', 'ioc14-hyd-min', '쇠갈매기', 'Hydrocoloeus minutus', 'Little Gull',
  '도요목', '갈매기과', 'rare', 3, 10,
  3, TRUE, NULL, 'LC',
  27,
  '해안과 하구에서 드물게 통과하는 소형 갈매기로 날개 아랫면이 어두운 것이 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠갈매기는 세계에서 가장 작은 갈매기로, 잠자리처럼 수면을 낮게 날며 곤충과 작은 어류를 잡습니다');

-- ============================================================
-- SECTION 2: 나그네새 (Migrant) — sensitivity_tier=3, points=3
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-232', 'ioc14-cha-dub', '꼬마물떼새', 'Charadrius dubius', 'Little Ringed Plover',
  '도요목', '물떼새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  16,
  '강자갈밭, 모래톱, 논에서 번식하며 발로 물을 일으켜 먹이를 유인하는 여름철새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '꼬마물떼새는 알을 자갈밭에 그냥 낳아 돌처럼 위장하며, 위협 시 다친 척 포식자를 유인합니다'),

('KR-233', 'ioc14-cha-ale', '흰물떼새', 'Charadrius alexandrinus', 'Kentish Plover',
  '도요목', '물떼새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  16,
  '해안 모래사장과 갯벌 상부에서 번식하는 여름철새로 가슴의 끊어진 띠가 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '흰물떼새는 새끼가 부화하면 즉시 부모를 따라 먹이를 찾아 뛰는 조숙성 조류입니다'),

('KR-234', 'ioc14-cha-mon', '왕눈물떼새', 'Charadrius mongolus', 'Lesser Sand Plover',
  '도요목', '물떼새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  20,
  '갯벌과 모래해변을 통과하며 조간대에서 소형 무척추동물을 먹는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '왕눈물떼새는 이름처럼 눈이 크고 동그란 것이 특징이며, 몽골 고원에서 번식하고 한국을 경유합니다'),

('KR-235', 'ioc14-cha-les', '큰왕눈물떼새', 'Charadrius leschenaultii', 'Greater Sand Plover',
  '도요목', '물떼새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  24,
  '갯벌과 해안 모래밭을 통과하는 나그네새로 왕눈물떼새보다 부리가 굵고 길다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '큰왕눈물떼새와 왕눈물떼새는 같은 갯벌을 공유하며 먹이 경쟁을 피해 서식 미세 구역을 나눕니다'),

('KR-236', 'ioc14-van-van', '댕기물떼새', 'Vanellus vanellus', 'Northern Lapwing',
  '도요목', '물떼새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'NT',
  30,
  '농경지와 습지에서 겨울을 나며 머리의 긴 댕기가 특징인 중형 물떼새',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '댕기물떼새는 날개의 넓은 검은-흰 무늬가 박수치는 것처럼 보이는 느린 날갯짓이 특징입니다'),

('KR-237', 'ioc14-plu-squ', '개꿩', 'Pluvialis squatarola', 'Grey Plover',
  '도요목', '물떼새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  28,
  '갯벌과 해안 조간대를 통과하는 중형 물떼새로 겨드랑이의 검은 반점이 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '개꿩은 겨울에는 회색이지만 번식기에는 가슴과 얼굴이 완전히 검게 변해 딴 새처럼 보입니다'),

('KR-238', 'ioc14-plu-ful', '금빛물떼새', 'Pluvialis fulva', 'Pacific Golden Plover',
  '도요목', '물떼새과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  25,
  '갯벌, 잔디밭, 농경지를 이동 시 통과하는 나그네새로 금빛 반점이 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '금빛물떼새는 알래스카에서 하와이까지 4,500km를 쉬지 않고 날아가는 장거리 이동 능력이 있습니다'),

('KR-239', 'ioc14-cha-pla', '흰목물떼새', 'Charadrius placidus', 'Long-billed Plover',
  '도요목', '물떼새과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  21,
  '강 자갈밭과 모래톱에서 번식하며 겨울에는 남하하는 여름철새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '흰목물떼새는 번식기에 강 자갈밭에서 흰 고리와 갈색 흉반이 선명해져 가장 아름다운 물떼새로 꼽힙니다'),

('KR-240', 'ioc14-tri-neb', '청다리도요', 'Tringa nebularia', 'Common Greenshank',
  '도요목', '도요과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  32,
  '갯벌과 강 하구에서 날카로운 "틱-틱-틱" 소리와 함께 통과하는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '청다리도요는 일렬로 달리며 물고기를 몰아 잡는 협력 사냥을 하는 드문 도요류입니다'),

('KR-241', 'ioc14-act-hyp', '삑삑도요', 'Actitis hypoleucos', 'Common Sandpiper',
  '도요목', '도요과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  20,
  '강과 하천을 따라 이동하며 꼬리를 끊임없이 위아래로 흔드는 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '삑삑도요는 걸을 때 마치 태엽 장난감처럼 몸 전체를 앞뒤로 끊임없이 흔드는 독특한 습성을 가집니다'),

('KR-242', 'ioc14-cal-alp', '민물도요', 'Calidris alpina', 'Dunlin',
  '도요목', '도요과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  19,
  '갯벌과 조간대에서 떼를 지어 통과하며 굽은 부리로 갯지렁이를 파내는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '민물도요 수만 마리의 집결 비행은 물결치듯 방향을 바꾸는 퍼포먼스로 갯벌의 대표 장관입니다'),

('KR-243', 'ioc14-cal-sub', '좀도요', 'Calidris subminuta', 'Long-toed Stint',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  14,
  '논과 내륙 습지를 이동 시 통과하는 소형 도요새로 발가락이 길어 수초를 타고 다닌다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '좀도요의 긴 발가락은 수련잎 위를 걸을 수 있게 해주는 놀라운 적응 형질입니다'),

('KR-244', 'ioc14-cal-acu', '메추라기도요', 'Calidris acuminata', 'Sharp-tailed Sandpiper',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  19,
  '갯벌과 논 습지를 통과하는 나그네새로 주황빛 가슴 줄무늬가 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '메추라기도요는 호주에서 시베리아까지 왕복 이동하며 한국 갯벌을 핵심 경유지로 이용합니다'),

('KR-245', 'ioc14-cal-alb', '세가락도요', 'Calidris alba', 'Sanderling',
  '도요목', '도요과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  20,
  '해안 모래사장에서 파도를 따라 달리며 작은 갑각류를 잡는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '세가락도요는 파도와의 쫓고 쫓기는 춤이 인상적이며, 파도에 쓸려 나온 작은 먹이를 순식간에 낚아챕니다'),

('KR-246', 'ioc14-xen-cin', '뒷부리도요', 'Xenus cinereus', 'Terek Sandpiper',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  23,
  '갯벌과 강 하구를 통과하는 나그네새로 위로 굽은 특이한 부리가 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '뒷부리도요의 독특하게 위로 굽은 부리는 갯벌 표면을 빠르게 훑어 먹이를 잡는 데 최적화됩니다'),

('KR-247', 'ioc14-gal-gal', '꺅도요', 'Gallinago gallinago', 'Common Snipe',
  '도요목', '도요과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  27,
  '논, 습지, 갈대밭에서 겨울을 나며 긴 부리를 진흙에 꽂아 지렁이를 잡는다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '꺅도요는 위험을 느끼면 "쐐기-쐐기" 소리와 함께 지그재그로 급상승 탈출하는 도요의 달인입니다'),

('KR-248', 'ioc14-gal-har', '큰꺅도요', 'Gallinago hardwickii', 'Latham''s Snipe',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  30,
  '논과 습지를 이동 시 통과하는 나그네새로 꺅도요보다 꼬리 깃 수가 많은 것이 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '큰꺅도요는 꼬리 깃을 16~20개 가지며 이 독특한 꼬리로 구애 비행 중 소리를 냅니다'),

('KR-249', 'ioc14-sco-rus', '멧도요', 'Scolopax rusticola', 'Eurasian Woodcock',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  34,
  '낙엽수림 바닥을 이동 시 경유하며 지렁이를 긴 부리로 파내 먹는 숲도요',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '멧도요의 눈은 머리 꼭대기에 달려 앞도 뒤도 위도 동시에 360° 시야로 볼 수 있습니다'),

('KR-250', 'ioc14-num-arq', '마도요', 'Numenius arquata', 'Eurasian Curlew',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'NT',
  55,
  '갯벌과 강 하구에서 긴 굽은 부리로 갯지렁이와 게를 깊이 파내 먹는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '마도요의 휘파람 같은 울음소리 "쿠루루루"는 갯벌의 가장 서정적인 배경 음악으로 알려져 있습니다'),

('KR-251', 'ioc14-pha-lob', '지느러미발도요', 'Phalaropus lobatus', 'Red-necked Phalarope',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  18,
  '해상과 해안을 통과하는 나그네새로 수면에서 빙글빙글 돌며 먹이를 잡는 독특한 행동을 한다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '지느러미발도요는 암컷이 더 화려하고 수컷이 홀로 알을 품는 역전된 성역할을 가진 드문 조류입니다'),

('KR-252', 'ioc14-tri-och', '깝작도요', 'Tringa ochropus', 'Green Sandpiper',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  23,
  '내륙 하천, 논, 습지를 이동 시 통과하며 날 때 흰 허리가 눈에 띄는 나그네새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '깝작도요는 다른 새의 묵은 둥지를 임시 번식지로 활용하는 효율적인 편의주의 번식 전략을 씁니다'),

('KR-253', 'ioc14-tri-sta', '학도요', 'Tringa stagnatilis', 'Marsh Sandpiper',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  23,
  '논과 습지를 이동 시 통과하는 소형 다리도요로 긴 다리와 직선형 부리가 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '학도요는 발이 마치 학처럼 길고 가늘어 얕은 물 위를 우아하게 걸으며 먹이를 찾습니다'),

('KR-254', 'ioc14-tri-gla', '붉은발도요', 'Tringa totanus', 'Common Redshank',
  '도요목', '도요과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  28,
  '갯벌과 논을 통과하며 날 때 흰 날개 뒷부분이 드러나는 붉은 발의 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '붉은발도요는 갯벌의 "경보기"로 불리며 위험을 발견하면 가장 먼저 큰 소리로 울어 동료들에게 알립니다'),

('KR-255', 'ioc14-num-pha', '쇠부리도요', 'Numenius minutus', 'Little Curlew',
  '도요목', '도요과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  32,
  '농경지와 초지를 이동 시 통과하는 도요류로 마도요보다 훨씬 작고 부리가 짧다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠부리도요는 이동 시 논과 초지에 내려앉는 드문 내륙형 도요로 목격 빈도가 낮습니다'),

('KR-256', 'ioc14-lar-arg', '재갈매기', 'Larus vegae', 'Vega Gull',
  '도요목', '갈매기과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  62,
  '서해·남해 연안과 강 하구에서 무리지어 월동하는 대형 갈매기',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '재갈매기는 조개를 높이 날아 바위나 아스팔트에 떨어뜨려 껍데기를 깨는 도구 사용 지능을 보입니다'),

('KR-257', 'ioc14-lar-cac', '큰재갈매기', 'Larus cachinnans', 'Caspian Gull',
  '도요목', '갈매기과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  60,
  '해안과 하구에서 드물게 월동하며 재갈매기와 혼서하는 대형 갈매기',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '큰재갈매기는 갈매기 분류 역사상 가장 논란이 많은 종 중 하나로 아종과 종 경계가 여전히 논의 중입니다'),

('KR-258', 'ioc14-chr-rid', '붉은부리갈매기', 'Chroicocephalus ridibundus', 'Black-headed Gull',
  '도요목', '갈매기과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  38,
  '해안, 강, 항구에서 무리지어 월동하며 번식기에 초콜릿색 머리를 가지는 중형 갈매기',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '붉은부리갈매기의 "검은머리"는 실제로 검정이 아닌 초콜릿 갈색이며 번식기에만 나타납니다'),

('KR-259', 'ioc14-lar-can', '갈매기', 'Larus canus', 'Mew Gull',
  '도요목', '갈매기과', 'migrant', 3, 3,
  1, FALSE, NULL, 'LC',
  43,
  '서해·남해 연안과 강 하구에서 월동하며 붉은부리갈매기와 함께 무리짓는 중형 갈매기',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '갈매기는 미성숙 개체가 성조가 되기까지 3~4년이 걸려 같은 종이라도 깃털 색이 전혀 달라 보입니다'),

('KR-260', 'ioc14-lar-hyp', '흰갈매기', 'Larus hyperboreus', 'Glaucous Gull',
  '도요목', '갈매기과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  72,
  '동해·서해 연안에 드물게 월동하는 대형 갈매기로 날개 끝이 흰 것이 특징이다',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '흰갈매기는 북극권에서 번식하고 겨울에 남하하는 북방 갈매기로, 흰 날개 끝이 유빙을 닮았습니다'),

('KR-261', 'ioc14-ste-hir', '제비갈매기', 'Sterna hirundo', 'Common Tern',
  '도요목', '갈매기과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  35,
  '해안과 강 모래톱에서 번식하며 공중에서 급강하해 물고기를 잡는 여름철새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '제비갈매기는 날개를 접고 화살처럼 수직 급강하해 정확히 물고기를 낚아채는 스카이다이빙 전문가입니다'),

('KR-262', 'ioc14-ste-alb', '쇠제비갈매기', 'Sternula albifrons', 'Little Tern',
  '도요목', '갈매기과', 'migrant', 3, 3,
  2, FALSE, NULL, 'LC',
  22,
  '해안 모래사장에서 번식하는 소형 제비갈매기로 이마의 흰 반점이 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '쇠제비갈매기는 해수욕장 모래사장에서 번식해 해변 개발과 인간 교란에 가장 취약한 제비갈매기입니다'),

('KR-263', 'ioc14-tha-ber', '큰제비갈매기', 'Thalasseus bergii', 'Greater Crested Tern',
  '도요목', '갈매기과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  47,
  '해안 해역을 통과하며 큰 물고기를 잡는 대형 제비갈매기',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '큰제비갈매기는 머리의 뾰족한 검은 댕기가 특징으로 제비갈매기류 중 가장 왕성한 어로 활동을 합니다'),

('KR-264', 'ioc14-tri-ery', '붉은어깨도요', 'Calidris tenuirostris', 'Great Knot',
  '도요목', '도요과', 'migrant', 3, 3,
  2, FALSE, NULL, 'EN',
  27,
  '서해안 갯벌에서 조개와 갯지렁이를 대량 섭취하며 중간 기착하는 나그네새',
  '{"jan":false,"feb":false,"mar":false,"apr":false,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '붉은어깨도요의 개체 수는 새만금 간척으로 핵심 경유지가 소실되며 30년간 80% 급감했습니다'),

('KR-265', 'ioc14-tri-inc', '도요사촌', 'Tringa incana', 'Wandering Tattler',
  '도요목', '도요과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  27,
  '암석 해안과 방파제를 이동 시 경유하는 바위 선호형 도요새',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '도요사촌은 파도에 씻기는 바위 위를 유유히 걷는 담력 있는 도요로, 태평양 도서를 오가며 이동합니다'),

('KR-266', 'ioc14-plu-apr', '황금물떼새', 'Pluvialis apricaria', 'European Golden Plover',
  '도요목', '물떼새과', 'migrant', 3, 3,
  3, FALSE, NULL, 'LC',
  28,
  '농경지와 초지를 드물게 통과하는 희귀 나그네새로 태평양황금물떼새와 유사하다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":false,"jun":false,"jul":false,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '황금물떼새는 번식기에 복부가 완전히 검게 변해 비번식기의 얼룩진 황금빛 모습과 전혀 달라 보입니다'),

('KR-267', 'ioc14-lim-hae', '흑꼬리도요', 'Limosa haemastica', 'Hudsonian Godwit',
  '도요목', '도요과', 'migrant', 3, 3,
  4, FALSE, NULL, 'LC',
  37,
  '대서양권 도요로 한국에는 매우 드물게 출현하는 미조',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '흑꼬리도요는 남북아메리카 사이를 이동하는 새이지만 간혹 동아시아에 미조로 나타나기도 합니다');

-- ============================================================
-- SECTION 3: 텃새 (Common) — sensitivity_tier=3, points=1
-- ============================================================

INSERT INTO species (species_id, ioc_taxon_id, name_ko, name_sci, name_en,
  order_ko, family_ko, rarity_tier, sensitivity_tier, points,
  aba_code, is_locked_free, cultural_heritage_no, iucn_status,
  size_cm, habitat_ko, seasonal_presence, fun_fact_ko)
VALUES

('KR-268', 'ioc14-lar-cra', '괭이갈매기', 'Larus crassirostris', 'Black-tailed Gull',
  '도요목', '갈매기과', 'common', 3, 1,
  1, FALSE, NULL, 'LC',
  47,
  '해안, 항구, 선착장에서 연중 볼 수 있는 한국의 가장 흔한 텃새 갈매기',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '괭이갈매기는 "괭-괭" 우는 소리가 고양이(괭이)와 비슷해 붙은 이름으로, 항구의 상징 새입니다'),

('KR-269', 'ioc14-hae-ost', '검은머리물떼새', 'Haematopus ostralegus', 'Eurasian Oystercatcher',
  '도요목', '검은머리물떼새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  43,
  '서해안 갯벌과 바위 해안에서 번식하며 굵은 붉은 부리로 홍합을 여는 텃새',
  '{"jan":true,"feb":true,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":true,"dec":true}',
  '검은머리물떼새는 홍합 열기에 두 가지 기술을 쓰는데, 찌르기형과 망치형 두 "학파"가 있습니다'),

('KR-270', 'ioc14-rec-avo', '장다리물떼새', 'Himantopus himantopus', 'Black-winged Stilt',
  '도요목', '장다리물떼새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  35,
  '논, 습지, 간척지에서 번식하는 여름철새로 새빨간 다리가 매우 긴 것이 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '장다리물떼새의 다리는 몸길이의 60%에 달해 조류 중 다리 비율이 가장 큰 새입니다'),

('KR-271', 'ioc14-rec-rec', '뒷부리장다리물떼새', 'Recurvirostra avosetta', 'Pied Avocet',
  '도요목', '장다리물떼새과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  43,
  '서해 간척지와 논에 드물게 나타나는 나그네새로 위로 굽은 부리가 특징이다',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '뒷부리장다리물떼새는 위로 굽은 부리를 물속에서 좌우로 저어 작은 갑각류를 잡는 독특한 섭식을 합니다'),

('KR-272', 'ioc14-bur-oed', '왕물떼새', 'Esacus recurvirostris', 'Great Stone-curlew',
  '도요목', '두툼이과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  55,
  '강 자갈밭과 모래사장에서 야간에 활동하는 대형 물떼새류',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '왕물떼새는 노란 눈이 야간 시력에 특화되어 어두운 강변에서 게와 개구리를 사냥합니다'),

('KR-273', 'ioc14-lob-lob', '흑부리갈매기', 'Ichthyaetus ichthyaetus', 'Pallas''s Gull',
  '도요목', '갈매기과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  72,
  '해안에 드물게 나타나는 대형 갈매기로 한국 기록이 많지 않은 미조',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '흑부리갈매기는 갈매기 중 가장 큰 편으로, 다른 갈매기에게서 먹이를 빼앗는 해적 행동을 보입니다'),

('KR-274', 'ioc14-ste-cas', '큰부리제비갈매기', 'Hydroprogne caspia', 'Caspian Tern',
  '도요목', '갈매기과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  53,
  '해안과 강 하구에서 드물게 관찰되는 대형 제비갈매기로 굵고 붉은 부리가 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '큰부리제비갈매기는 소리 크고 공격적이어서 다른 새들이 주변에 둥지 틀기를 꺼리는 무서운 이웃입니다'),

('KR-275', 'ioc14-chi-hyb', '흰수염제비갈매기', 'Chlidonias hybrida', 'Whiskered Tern',
  '도요목', '갈매기과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  26,
  '내륙 습지와 논을 통과하는 소형 제비갈매기로 수초 위에서 곤충을 잡는다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '흰수염제비갈매기는 내륙 습지를 선호하는 제비갈매기로 잠수하지 않고 수면에서 먹이를 낚아챕니다'),

('KR-276', 'ioc14-chi-nig', '검은제비갈매기', 'Chlidonias niger', 'Black Tern',
  '도요목', '갈매기과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  23,
  '해안과 내륙 수면을 통과하는 드문 나그네새로 비번식기에 흑백 무늬가 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '검은제비갈매기는 번식기에 몸 전체가 검게 변해 비번식기의 흑백 개체와 전혀 다른 모습입니다'),

('KR-277', 'ioc14-cal-tem', '종다리도요', 'Calidris temminckii', 'Temminck''s Stint',
  '도요목', '도요과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  14,
  '논과 내륙 습지를 통과하는 소형 도요새로 갯벌보다 내륙 환경을 선호한다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '종다리도요는 흰 바깥꼬리와 노란빛 다리로 비슷한 소형 도요들과 구별되는 내륙형 나그네새입니다'),

('KR-278', 'ioc14-cal-pus', '붉은가슴흰죽지도요', 'Calidris ruficollis', 'Red-necked Stint',
  '도요목', '도요과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  14,
  '갯벌과 논 습지를 이동 시 통과하는 소형 도요새로 번식기에 목이 붉다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '붉은가슴흰죽지도요는 엄지손톱만한 작은 몸으로 시베리아에서 호주까지 매년 왕복 이동합니다'),

('KR-279', 'ioc14-cal-min', '꼬마도요', 'Calidris minuta', 'Little Stint',
  '도요목', '도요과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  13,
  '갯벌과 논 습지를 드물게 통과하는 희귀 나그네새로 붉은가슴흰죽지도요와 유사하다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '꼬마도요는 유럽-아프리카 계통의 도요로 한국에서 발견되면 희귀 기록으로 보고됩니다'),

('KR-280', 'ioc14-van-cin', '민댕기물떼새', 'Vanellus cinereus', 'Grey-headed Lapwing',
  '도요목', '물떼새과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  35,
  '논, 농경지, 습지에서 이동 시 통과하거나 드물게 번식하는 중형 물떼새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":true,"jul":true,"aug":true,"sep":true,"oct":true,"nov":false,"dec":false}',
  '민댕기물떼새는 댕기물떼새와 달리 머리가 회색이고 댕기가 없어 더 단아한 인상을 줍니다'),

('KR-281', 'ioc14-cha-his', '왜가리물떼새', 'Esacus magnirostris', 'Beach Stone-curlew',
  '도요목', '두툼이과', 'common', 3, 1,
  4, FALSE, NULL, 'LC',
  57,
  '해안과 산호초 지역의 미조로 한국에 극히 드물게 출현한다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '왜가리물떼새는 야행성으로 낮에는 해변에 웅크려 있다가 밤에 게와 소형 동물을 사냥합니다'),

('KR-282', 'ioc14-ros-ros', '분홍발기러기', 'Anser brachyrhynchus', 'Pink-footed Goose',
  '기러기목', '오리과', 'common', 3, 1,
  4, FALSE, NULL, 'LC',
  70,
  '서해안 논과 갯벌에 극히 드물게 나타나는 기러기무리의 미조',
  '{"jan":true,"feb":true,"mar":true,"apr":false,"may":false,"jun":false,"jul":false,"aug":false,"sep":false,"oct":true,"nov":true,"dec":true}',
  '분홍발기러기는 주로 북유럽-아이슬란드에 번식하며 한국에 출현하면 항상 뉴스가 되는 희귀 방문객입니다'),

('KR-283', 'ioc14-ste-dou', '흰죽지제비갈매기', 'Chlidonias leucopterus', 'White-winged Tern',
  '도요목', '갈매기과', 'common', 3, 1,
  2, FALSE, NULL, 'LC',
  22,
  '내륙 습지와 논을 통과하는 소형 제비갈매기로 번식기에 날개가 흰빛이 도는 것이 특징이다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '흰죽지제비갈매기는 번식기의 극적인 흑백 대비 무늬와 비번식기의 얼룩진 모습이 전혀 다르게 보입니다'),

('KR-284', 'ioc14-tri-fla', '노랑발도요', 'Tringa flavipes', 'Lesser Yellowlegs',
  '도요목', '도요과', 'common', 3, 1,
  4, FALSE, NULL, 'LC',
  24,
  '북미 산 도요로 한국에 아주 드물게 미조로 나타난다',
  '{"jan":false,"feb":false,"mar":false,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '노랑발도요는 붉은발도요와 유사하지만 노란 다리와 가는 부리로 구별되며 한국에서 기록되면 희귀종 보고가 됩니다'),

('KR-285', 'ioc14-cal-mau', '세가락메추라기', 'Turnix sylvaticus', 'Small Buttonquail',
  '도요목', '세가락메추라기과', 'common', 3, 1,
  3, FALSE, NULL, 'LC',
  14,
  '농경지와 풀밭에 드물게 출현하는 소형 메추라기 모양의 새',
  '{"jan":false,"feb":false,"mar":true,"apr":true,"may":true,"jun":false,"jul":false,"aug":true,"sep":true,"oct":false,"nov":false,"dec":false}',
  '세가락메추라기는 발가락이 세 개이며 암컷이 더 화려하고 수컷이 알을 품는 역할 역전 번식 전략을 씁니다');

COMMIT;

-- DOWN
BEGIN;
DELETE FROM species WHERE species_id IN (
  'KR-226','KR-227','KR-228','KR-229','KR-230','KR-231','KR-232','KR-233',
  'KR-234','KR-235','KR-236','KR-237','KR-238','KR-239','KR-240','KR-241',
  'KR-242','KR-243','KR-244','KR-245','KR-246','KR-247','KR-248','KR-249',
  'KR-250','KR-251','KR-252','KR-253','KR-254','KR-255','KR-256','KR-257',
  'KR-258','KR-259','KR-260','KR-261','KR-262','KR-263','KR-264','KR-265',
  'KR-266','KR-267','KR-268','KR-269','KR-270','KR-271','KR-272','KR-273',
  'KR-274','KR-275','KR-276','KR-277','KR-278','KR-279','KR-280','KR-281',
  'KR-282','KR-283','KR-284','KR-285'
);
COMMIT;
